---
name: Continuous Integration

# yamllint disable-line rule:truthy
on:
  - push

jobs:
  source-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run CI tasks
        run: |
          poetry run black --check src tests
          poetry run mypy src tests
          poetry run pytest
